version: '2.3'

services:

   api:
     image: iteastyle-api
     build: .
     container_name: iteastyle-api
     restart: always
     expose:
           - "443"
     environment:
       VIRTUAL_HOST: iteastyle-api.aimeow.com
       VIRTUAL_PORT: 8080
       LETSENCRYPT_HOST: iteastyle-api.aimeow.com
       LETSENCRYPT_EMAIL: a18814888787@gmail.com

networks:
    default:
       external:
         name: nginx-proxy