version: '2.4'

services:

   api:
     image: iteastyle-api-test
     build: .
     container_name: iteastyle-api-test
     restart: always
     expose:
           - "15505"
     environment:
       VIRTUAL_HOST: iteastyle-api-test.aimeow.com
       VIRTUAL_PORT: 8080
       LETSENCRYPT_HOST: iteastyle-api-test.aimeow.com
       LETSENCRYPT_EMAIL: a18814888787@gmail.com

networks:
    default:
       external:
         name: nginx-proxy